general:
  productiveBranch: 'infrastructure-integration-test-neo'
  collectTelemetryData: false
steps:
  deployToNeoWithCli:
    dockerImage: 'localhost:5000/ppiper/neo-cli'
stages:
  npmAudit:
    auditedAdvisories:
      - 803
  productionDeployment:
    neoTargets:
      - host: 'eu1.hana.ondemand.com'
        account: 's7am47zded'
        application: 'devopsdockerimagesitonneo'
        credentialsId: 'devops-docker-images-IT-cf'
        runtime: 'neo-javaee7-wp'
        runtimeVersion: '1'
